### ISSUE TITLE
Feature request: Ability to construct `Weak<T>` from `RcBorrow<T>`

### ISSUE THREAD

**Issue by yvt** [CAD97/pointer-utils#58]
Currently, one has to first convert `[A]rcBorrow` to `[A]rc` before obtaining `Weak`. It would be great if `Weak` could be constructed directly without this extra step.

**Comment by CAD97** [comment]
Yeah, I agree, this is useful. #59 implements the functionality.

In retrospect, I wish `downgrade` returned a `Weak` instead of `&'a T`. Do you have any suggestions for what to call this function?

**Comment by yvt** [comment]
> do you have any other suggestions for what this method should be called?

Sorry, I don't have any. It's really a shame that `downgrade` is already taken.

How do you feel about redoing the naming scheme in the next major version (0.2.x)? This would be a breaking change, but the impact of introducing breaking changes tends to accumulate as you try to defer it, which makes it important to iron out any API design issues at the earliest moment possible (this needs to be balanced against annoyance to users, though). I think this is the point of pre-1.0 versions.

**Comment by CAD97** [comment]
rc-borrow is already v1.0. All of pointer-utils is: it was important to me to signal that these utilities are "production worthy," so I published them at 1.0.

On top of this, [`A`]`RcBorrow` is a type intended to be used in public APIs. This makes breaking changes more problematic, as they necessarily cascade into people who use rc-borrow, rather than being self-contained.

The point is that rc-borrow doesn't _need_ breaking changes, and it won't need breaking changes; the core functionality works as intended and doesn't need API-breaking changes.

It'll be sad to lose `downgrade`, but maybe deprecating `downgrade` and adding `[in]to_weak` and `[in]to_ref` wouldn't be too bad.

**Comment by yvt** [comment]
Hmm, I wonder why I thought `rc-borrow` was still at 0.1.x. Anyway, In that case, I agree that the ship has already sailed.

> It'll be sad to lose `downgrade`, but maybe deprecating `downgrade` and adding `[in]to_weak` and `[in]to_ref` wouldn't be too bad.

Considering the current circumstance, this sounds good to me, except that I feel `as_ref` is more apt according to [the style guide](https://doc.rust-lang.org/1.0.0/style/style/naming/conversions.html).

**Comment by CAD97** [comment]
I just added `to_weak` in #59 and will hopefully publish this soon-ish.

I'll consider renaming `downgrade` in the future, but `to_weak` is nonproblematic to add right now.

**Comment by CAD97** [comment]
Published as v1.3.0 🎉
