### ISSUE TITLE
slice-dst feature request: from_raw_parts

### ISSUE THREAD

**Issue by Ralith** [CAD97/pointer-utils#63]
I'd love to see a function along the lines of
```rust
pub unsafe fn from_raw_parts<Header, Item>(header: *mut Header, len: usize) -> &SliceWithHeader<Header, Item>
```
As written, I think this is prevented by the `length` field on `SliceWithHeader`, but maybe a different slice type without that field could be introduced?

My use case is that I have mapped memory from a graphics device, and I want to overlay a DST onto it for convenient access before transferring data to device-local memory.

**Comment by CAD97** [comment]
I think that this is too subtly dangerous to expose a helper for.

Rather than use `[Slice]WithHeader`, I'd suggest making your own `#[repr(C)]` descriptor of the mapped memory, then casting the pointer yourself. This is more obvious about what you're doing, and more obviously correct, since you have the layout defined right there, rather than relying on how `[Slice]WithHeader` is defined.

(As an example, abusing fake nested struct syntax:

```rust
#[repr(C)]
struct Example {
    header: struct Header { a: u32, b: u8 },
    tail: [u8],
}
```

will have a 3 byte padding between `.header.b` and `.tail`, that wouldn't exist if the fields are inlined, because struct size is struct stride is a multiple of alignment.)

The conversion from `*mut c_void` to `*mut YourMMStruct` isn't actually all that problematic: use [`std::ptr::slice_from_raw_parts`](https://doc.rust-lang.org/std/ptr/fn.slice_from_raw_parts_mut.html) and just cast to a pointer to your struct: `ptr::slice_from_raw_parts(ptr, len) as *mut YourMMStruct`.

**Comment by Ralith** [comment]
That makes total sense; thanks for outlining the approach! Makes me look forward to the layout manipulation tools you talked about getting into std, too.
