### ISSUE TITLE
slice-dst: Vec / String / Box conversions

### ISSUE THREAD

**Issue by jplatte** [CAD97/pointer-utils#65]
Would it be possible for slice-dst to provide conversion functions between `SliceWithHeader` and regular boxed slices + `Vec` and the same thing for `StrWithHeader` and boxed string slices + `String` that reuse the allocation?

**Comment by CAD97** [comment]
> reuse the allocation

This just straight isn't possible. The point of these types is to store data alongside the slice data in the same allocation, so the previous allocation for just the slice isn't going to be large enough. On top of this, it's extremely important that the final allocation is the exact required size, because that's the semantics that `Box` expects for its allocations.

Even in the rare occasion where we can [`realloc`](https://doc.rust-lang.org/std/alloc/fn.realloc.html) for cheaper than a new allocation, we still have to do an overlapping copy of the slice to the end of the allocation (rather than the front where it is for non-wrapped cases).

Conversions from `Vec<T>`/`Box<[T]>` would be able to do one singular thing better: they could do the new allocation and a simple `copy_nonoverlapping` of the old data into the new place, rather than having to go through the complexity of the panic-correct iterator-taking version. (This is already the case for the `&str` version.) However, I don't think the added API complexity is worth it for the small improvement in codegen, especially given they might mislead users into thinking they reuse the allocation (which, again, is impossible).
